[build]
  publish = "frontend/build"  # Ensures only the frontend build folder is published
  base = "."  # Ensures Netlify uses the root directory as the base

[dev]
  framework = "create-react-app"
  command = "npm run dev"
